---
title: "Part 2: Is There Bias from Day One?"
author: "April Nian"
date: "2026-03-02"
---

After reviewing the introduction and gaining a brief understanding of the data we are working with in this analysis, consider this question to yourself;

“Does wage discrimination actually exist in the **starting salaries** between men and women faculty members?” 

What is the instinctive answer that comes to your mind?

Well, to determine if a bias actually exists in the starting salaries, we will first have to adjust our data from our original dataset, with almost 20,000 entries, to a dataset which only looks at salary in a professor’s starting year. What we noticed was that since the original data was recorded from 1976 to 1995, not all faculty members had a recorded starting salary. So we went from the original 1,597 faculty to only 1,107!

We then used two simple methods to test for the difference in between the starting salary of men and women, one testing for a difference in the average starting salary of the two groups and another testing for whether gender had an effect on salary when other variables are taken into consideration. 

We first calculated the average starting salary of men to be \$4015.55 and the average starting salary for women to be \$3600.32, which displays an obvious difference of \$415.23. We then used statistical analysis to determine if this was a significant difference and we found that it was! 

This suggests that assuming salary is only affected by gender, male faculty members on average make \$415.23 more than women faculty members!

Now you may be an astute reader and have noticed the super important phrasing of “assuming salary is only affected by gender”. Do you think gender still has an effect on salary when other predictor variables are included?

We conducted a second approach to verify the effect of gender on salary by testing a base model (where “sex” is not included) and a full model (where “sex” is included) to see if there is a significant effect of gender on salary when other aspects such as the starting year, field, rank etc. are incorporated into the model. It turns out that after controlling for all other predictor variables, sex still explains a significant amount of variation in salary.

From our analysis, we found that starting year, field, admin, and rank also had significant effects on starting salaries. When we take these four variables into account, the effect of gender on starting salary also changed as described below. When all other variables are held constant:

-   Male faculty members' starting salary is 5.46% higher than their female counterparts.

-   Professors in the field categorized as “Other” have a starting salary that is 10.89% higher than those in the “Arts”.

-   Professors in the Professional field have a starting salary that is 24.99% higher than those in the “Arts”.

-   Faculty members with administration experience have a starting salary that is 13.57% higher than faculty members without administration experience.

-   Faculty members ranked as “Associate” have a starting salary that is 26.17% higher than faculty members ranked as “Assistant”.

-   Faculty members ranked as “Full” have a starting salary that is 79.49% higher than faculty members ranked as Assistant.\

When looking at the starting year, starting salary increases by 5.77% per year, which is a potential indication for inflation. 

So to answer the question in short, **Yes**! **wage discrimination does exist in the starting salaries of men and women faculty members!**  This is reflected in both the average starting salary and the effect of gender on salary when other variables are incorporated. Although starting salary is also affected by categories such as rank, field, and admin, and even more affected by the starting year, the test conducted in this analysis provides significant evidence of a difference between the starting salaries of women and men faculty members in general.
